api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/npm-install"
  id = "paketo-buildpacks/npm-install"
  name = "Paketo NPM Install Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
